// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'AkarIcons:check': typeof import('virtual:vite-icons/akar-icons/check')['default']
    'AkarIcons:clipboard': typeof import('virtual:vite-icons/akar-icons/clipboard')['default']
    CarbonCampsite: typeof import('virtual:vite-icons/carbon/campsite')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('virtual:vite-icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
  }
}

export { }
