// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'AkarIcons:check': typeof import('virtual:vite-icons/akar-icons/check')['default']
    'AkarIcons:clipboard': typeof import('virtual:vite-icons/akar-icons/clipboard')['default']
    CarbonCampsite: typeof import('virtual:vite-icons/carbon/campsite')['default']
  }
}

export { }
